const express = require('express');
const helmet = require('helmet');
const path = require('path');
const app = express();
app.set('trust proxy', 1);
const PORT = Number(process.env.PORT) || 3000;
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],imgSrc:["'self'","data:"],connectSrc:["'self'"],fontSrc:["'self'","data:"],objectSrc:["'none'"],frameAncestors:["'none'"],upgradeInsecureRequests:null}}}));
app.use(express.json({limit:'12kb'}));
app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(_req,res)=>res.json({ok:true,aiConfigured:Boolean(process.env.GEMINI_API_KEY),model:process.env.GEMINI_MODEL||'gemini-2.5-flash'}));
// Basic per-IP request guard; not a substitute for a managed API gateway.
const requestLog=new Map(), WINDOW=60000, LIMIT=12;
function rateLimit(req,res,next){const key=req.ip||req.socket.remoteAddress||'unknown',now=Date.now(),recent=(requestLog.get(key)||[]).filter(t=>now-t<WINDOW);if(recent.length>=LIMIT){res.set('Retry-After','60');return res.status(429).json({error:'थोड़ा रुककर फिर कोशिश करें। एक मिनट में AI requests की सीमा पूरी हो गई है।'});}recent.push(now);requestLog.set(key,recent);if(requestLog.size>1500)for(const [ip,times] of requestLog)if(!times.some(t=>now-t<WINDOW))requestLog.delete(ip);next();}
const SYSTEM_INSTRUCTION=`You are Eco Sparks, a practical, friendly assistant inside Smart Energy Saver. Reply in the requested language: en = English, hi = natural Hindi in Devanagari, hinglish = natural Roman-script Hindi mixed with English. Use a warm, human conversational tone. You represent the Eco Sparks team. Do not proactively mention underlying model or provider names. If directly asked who powers you, answer truthfully and never falsely claim Eco Sparks trained the foundation model. Help with energy saving, estimated bills, appliance use, basic electrical engineering, safe troubleshooting, and questions to ask a qualified electrician. Use household context as estimates, not meter-grade facts. Show formulas and units for calculations. Never give instructions to touch live wiring, open an energized distribution board, bypass an MCB/RCD/earthing, defeat safety interlocks, or work on high voltage. For sparks, burning smell, shocks, hot sockets, exposed wires, repeated breaker trips, or water near electricity, tell the user to stay away, turn off power only if safely possible without approaching danger, and contact a qualified electrician/emergency service. Do not ask for secrets or API keys. Distinguish safe visual checks from work for a qualified electrician.`;
app.post('/api/chat',rateLimit,async(req,res)=>{
 const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return res.status(503).json({error:'AI अभी configure नहीं है। Owner को Render Environment में GEMINI_API_KEY जोड़ना होगा।'});
 const message=typeof req.body?.message==='string'?req.body.message.trim():'';const mode=typeof req.body?.mode==='string'?req.body.mode.slice(0,40):'general';const raw=req.body?.context&&typeof req.body.context==='object'?req.body.context:{};
 if(!message)return res.status(400).json({error:'अपना सवाल लिखें।'});if(message.length>1500)return res.status(413).json({error:'सवाल 1500 characters से छोटा रखें।'});
 const num=(v,min,max)=>{const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:undefined;};
 const context={dailyKwh:num(raw.dailyKwh,0,1e7),monthlyKwh:num(raw.monthlyKwh,0,1e8),monthlyBill:num(raw.monthlyBill,0,1e10),tariff:num(raw.tariff,0,1000),appliances:Array.isArray(raw.appliances)?raw.appliances.slice(0,12).map(a=>({name:String(a?.name||'Appliance').slice(0,60),watts:num(a?.watts,0,100000)||0,quantity:num(a?.quantity,1,100)||1,hours:num(a?.hours,0,24)||0})):[]};
 const model=(process.env.GEMINI_MODEL||'gemini-2.5-flash').trim();const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),35000);
 try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:SYSTEM_INSTRUCTION}]},contents:[{role:'user',parts:[{text:`Assistant mode: ${mode}. Requested language: ${["en","hi","hinglish"].includes(req.body?.language) ? req.body.language : "en"}. Estimated household context: ${JSON.stringify(context)}. User question: ${message}`}]}],generationConfig:{temperature:.45,maxOutputTokens:900}}),signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok){console.error('Gemini status:',response.status);if(response.status===401||response.status===403)return res.status(502).json({error:'AI configuration में समस्या है। Website owner को server API key और access जाँचना होगा।'});if(response.status===429)return res.status(429).json({error:'AI request limit अभी पूरी हो सकती है। थोड़ी देर बाद कोशिश करें।'});return res.status(502).json({error:'AI service से जवाब नहीं मिला। थोड़ी देर बाद कोशिश करें।'});}const answer=(data.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n').trim();if(!answer)return res.status(502).json({error:'AI ने खाली जवाब दिया। सवाल को थोड़ा बदलकर पूछें।'});return res.json({answer});}
 catch(err){if(err.name==='AbortError')return res.status(504).json({error:'AI को जवाब देने में ज्यादा समय लगा। फिर कोशिश करें।'});console.error('AI request failed:',err.message);return res.status(502).json({error:'Internet या AI service में अस्थायी समस्या है।'});}finally{clearTimeout(timeout);}
});
app.get('*splat',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`Smart Energy Saver listening on ${PORT}`));
