const express = require('express');
const helmet = require('helmet');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const app = express();
app.set('trust proxy', 1);
const PORT = Number(process.env.PORT) || 3000;
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],imgSrc:["'self'","data:"],connectSrc:["'self'"],fontSrc:["'self'","data:"],objectSrc:["'none'"],frameAncestors:["'none'"],upgradeInsecureRequests:null}}}));
app.use(express.json({limit:'12kb'}));
app.use(express.static(path.join(__dirname,'public')));
// Lightweight file-backed account store for demos. Render's free filesystem is ephemeral;
// configure a persistent disk or database for production deployments.
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const USERS_FILE=path.join(DATA_DIR,'users.json');
fs.mkdirSync(DATA_DIR,{recursive:true});
function readUsers(){try{return JSON.parse(fs.readFileSync(USERS_FILE,'utf8'))}catch{return []}}
function writeUsers(users){fs.writeFileSync(USERS_FILE,JSON.stringify(users,null,2),{mode:0o600})}
const SESSION_SECRET=process.env.SESSION_SECRET||'';
function sign(value){return crypto.createHmac('sha256',SESSION_SECRET).update(value).digest('hex')}
function sessionToken(payload){const data=Buffer.from(JSON.stringify({...payload,exp:Date.now()+7*86400000})).toString('base64url');return data+'.'+sign(data)}
function readSession(req){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('eco_session='))?.slice(12);if(!raw||!SESSION_SECRET)return null;const [data,sig]=raw.split('.');if(!data||!sig)return null;const expected=Buffer.from(sign(data)),provided=Buffer.from(sig);if(provided.length!==expected.length||!crypto.timingSafeEqual(provided,expected))return null;try{const v=JSON.parse(Buffer.from(data,'base64url').toString());return v.exp>Date.now()?v:null}catch{return null}}
function setSession(res,payload){res.setHeader('Set-Cookie',`eco_session=${sessionToken(payload)}; HttpOnly; ${process.env.NODE_ENV==='production'?'Secure; ':''}SameSite=Lax; Path=/; Max-Age=604800`)}
function auth(req,res,next){const u=readSession(req);if(!u)return res.status(401).json({error:'Please log in to continue.'});req.user=u;next()}
app.get('/api/auth/status',(req,res)=>{const u=readSession(req);res.json({authenticated:!!u,user:u?{consumerNo:u.consumerNo,name:u.name,role:u.role}:null,authReady:!!SESSION_SECRET,adminReady:!!process.env.ADMIN_PASSWORD})});
app.post('/api/auth/register',async(req,res)=>{if(!SESSION_SECRET)return res.status(503).json({error:'Login system is not configured. Admin must set SESSION_SECRET on the server.'});const consumerNo=String(req.body?.consumerNo||'').trim().replace(/\s+/g,'');const name=String(req.body?.name||'').trim().slice(0,60);const pin=String(req.body?.pin||'');if(!/^[A-Za-z0-9-]{4,24}$/.test(consumerNo)||name.length<2||!/^[0-9]{4,8}$/.test(pin))return res.status(400).json({error:'Enter a name, consumer number (4–24 letters/numbers) and 4–8 digit PIN.'});const users=readUsers();if(users.some(u=>u.consumerNo.toLowerCase()===consumerNo.toLowerCase()))return res.status(409).json({error:'That consumer number already has an account.'});const salt=crypto.randomBytes(16).toString('hex');const pinHash=crypto.scryptSync(pin,salt,64).toString('hex');const user={id:crypto.randomUUID(),consumerNo,name,salt,pinHash,role:'user',createdAt:new Date().toISOString(),active:true};users.push(user);writeUsers(users);setSession(res,{id:user.id,consumerNo:user.consumerNo,name:user.name,role:'user'});res.status(201).json({ok:true,user:{consumerNo,name,role:'user'}})});
app.post('/api/auth/login',(req,res)=>{if(!SESSION_SECRET)return res.status(503).json({error:'Login system is not configured.'});const consumerNo=String(req.body?.consumerNo||'').trim();const pin=String(req.body?.pin||'');const u=readUsers().find(x=>x.consumerNo.toLowerCase()===consumerNo.toLowerCase()&&x.active!==false);if(!u||!crypto.timingSafeEqual(Buffer.from(crypto.scryptSync(pin,u.salt,64)),Buffer.from(u.pinHash,'hex')))return res.status(401).json({error:'Consumer number or PIN is incorrect.'});setSession(res,{id:u.id,consumerNo:u.consumerNo,name:u.name,role:'user'});res.json({ok:true,user:{consumerNo:u.consumerNo,name:u.name,role:'user'}})});
app.post('/api/auth/admin',(req,res)=>{const pass=String(req.body?.password||'');if(!SESSION_SECRET||!process.env.ADMIN_PASSWORD)return res.status(503).json({error:'Admin login is not configured. Set ADMIN_PASSWORD and SESSION_SECRET in Render Environment.'});const a=Buffer.from(pass),b=Buffer.from(process.env.ADMIN_PASSWORD);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'Admin password is incorrect.'});setSession(res,{id:'admin',consumerNo:'ADMIN',name:'Admin',role:'admin'});res.json({ok:true,user:{consumerNo:'ADMIN',name:'Admin',role:'admin'}})});
app.post('/api/auth/logout',(req,res)=>{res.setHeader('Set-Cookie','eco_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/admin/users',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required.'});res.json({users:readUsers().map(({id,consumerNo,name,createdAt,active})=>({id,consumerNo,name,createdAt,active}))})});
app.patch('/api/admin/users/:id',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required.'});const users=readUsers(),u=users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'User not found.'});if(typeof req.body?.active==='boolean')u.active=req.body.active;writeUsers(users);res.json({ok:true})});
app.delete('/api/admin/users/:id',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required.'});writeUsers(readUsers().filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.get('/api/health',(_req,res)=>res.json({ok:true,aiConfigured:Boolean(process.env.GEMINI_API_KEY),model:process.env.GEMINI_MODEL||'gemini-2.5-flash'}));
// Basic per-IP request guard; not a substitute for a managed API gateway.
const requestLog=new Map(), WINDOW=60000, LIMIT=12;
function rateLimit(req,res,next){const key=req.ip||req.socket.remoteAddress||'unknown',now=Date.now(),recent=(requestLog.get(key)||[]).filter(t=>now-t<WINDOW);if(recent.length>=LIMIT){res.set('Retry-After','60');return res.status(429).json({error:'थोड़ा रुककर फिर कोशिश करें। एक मिनट में AI requests की सीमा पूरी हो गई है।'});}recent.push(now);requestLog.set(key,recent);if(requestLog.size>1500)for(const [ip,times] of requestLog)if(!times.some(t=>now-t<WINDOW))requestLog.delete(ip);next();}
const SYSTEM_INSTRUCTION=`You are Eco Sparks, a practical, friendly assistant inside Smart Energy Saver. Reply in the requested language: en = English, hi = natural Hindi in Devanagari, hinglish = natural Roman-script Hindi mixed with English. Use a warm, natural tone. Keep answers medium length: normally 3–5 concise bullets or 2–4 short paragraphs, about 80–160 words unless the user explicitly asks for detail. Avoid essays, repeated introductions, filler, and unsolicited long safety lectures; give only the safety warning relevant to the question. Answer the user directly without commenting on their language setting. Brand yourself as Eco Sparks. Do not mention Google, Gemini, or other provider/model brands; if asked who made you, say you are Eco Sparks, created for the Smart Energy Saver project by the team listed in About Us, without making claims about model training. Help with energy saving, estimated bills, appliance use, basic electrical engineering, safe troubleshooting, and questions to ask a qualified electrician. Use household context as estimates, not meter-grade facts. Show formulas and units for calculations. Never give instructions to touch live wiring, open an energized distribution board, bypass an MCB/RCD/earthing, defeat safety interlocks, or work on high voltage. For sparks, burning smell, shocks, hot sockets, exposed wires, repeated breaker trips, or water near electricity, tell the user to stay away, turn off power only if safely possible without approaching danger, and contact a qualified electrician/emergency service. Do not ask for secrets or API keys. Distinguish safe visual checks from work for a qualified electrician.`;
app.post('/api/chat',rateLimit,async(req,res)=>{
 const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return res.status(503).json({error:'AI अभी configure नहीं है। Owner को Render Environment में GEMINI_API_KEY जोड़ना होगा।'});
 const message=typeof req.body?.message==='string'?req.body.message.trim():'';const mode=typeof req.body?.mode==='string'?req.body.mode.slice(0,40):'general';const raw=req.body?.context&&typeof req.body.context==='object'?req.body.context:{};
 if(!message)return res.status(400).json({error:'अपना सवाल लिखें।'});if(message.length>1500)return res.status(413).json({error:'सवाल 1500 characters से छोटा रखें।'});
 const num=(v,min,max)=>{const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:undefined;};
 const context={dailyKwh:num(raw.dailyKwh,0,1e7),monthlyKwh:num(raw.monthlyKwh,0,1e8),monthlyBill:num(raw.monthlyBill,0,1e10),tariff:num(raw.tariff,0,1000),appliances:Array.isArray(raw.appliances)?raw.appliances.slice(0,12).map(a=>({name:String(a?.name||'Appliance').slice(0,60),watts:num(a?.watts,0,100000)||0,quantity:num(a?.quantity,1,100)||1,hours:num(a?.hours,0,24)||0})):[]};
 const model=(process.env.GEMINI_MODEL||'gemini-2.5-flash').trim();const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),35000);
 try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:SYSTEM_INSTRUCTION}]},contents:[{role:'user',parts:[{text:`Assistant mode: ${mode}. Requested language: ${["en","hi","hinglish"].includes(req.body?.language) ? req.body.language : "en"}. Estimated household context (may be empty and is not guaranteed to describe the user): ${JSON.stringify(context)}. Never invent appliance quantities, wattages, daily hours, tariff, or bill values. If needed details are missing, give general tips or clearly label examples as assumptions. For savings estimates, show the formula and state assumptions; do not present invented user data as facts. Use plain text with short headings/bullets; avoid raw Markdown syntax such as literal ** around labels. User question: ${message}`}]}],generationConfig:{temperature:.3,maxOutputTokens:380}}),signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok){console.error('Gemini status:',response.status);if(response.status===401||response.status===403)return res.status(502).json({error:'AI configuration में समस्या है। Website owner को server API key और access जाँचना होगा।'});if(response.status===429)return res.status(429).json({error:'AI request limit अभी पूरी हो सकती है। थोड़ी देर बाद कोशिश करें।'});return res.status(502).json({error:'AI service से जवाब नहीं मिला। थोड़ी देर बाद कोशिश करें।'});}const answer=(data.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n').trim();if(!answer)return res.status(502).json({error:'AI ने खाली जवाब दिया। सवाल को थोड़ा बदलकर पूछें।'});return res.json({answer});}
 catch(err){if(err.name==='AbortError')return res.status(504).json({error:'AI को जवाब देने में ज्यादा समय लगा। फिर कोशिश करें।'});console.error('AI request failed:',err.message);return res.status(502).json({error:'Internet या AI service में अस्थायी समस्या है।'});}finally{clearTimeout(timeout);}
});
app.get('*splat',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`Smart Energy Saver listening on ${PORT}`));
